version: '3.0'

services:
  ##### uncomment this for running from docker hub #####
  # web:
  #   container_name: store-web
  #   image: rereasdev/eniqilo-store:latest
  #   env_file:
  #     - eniqilo-store.env
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - eniqilo

  web:
    build: .
    container_name: store-web
    env_file:
      - eniqilo-store.env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: air main.go -b 0.0.0.0
    networks:
      - eniqilo

  db:
    container_name: store-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store-db
      - POSTGRES_HOST=store-db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgres/data
    networks:
      - eniqilo

networks:
  eniqilo:
    external: true
