version: '3.0'

services:
  web:
    build: .
    container_name: store-web
    env_file:
      - eniqilo-store.env
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: air main.go -b 0.0.0.0

  db:
    container_name: store-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=store-db
      - POSTGRES_HOST=store-db
    ports:
      - 5432:5432
    # volumes:
    #   - ./db-data:/var/lib/postgres/data
